package grpcep

import (
	"io"

	gogoproto "github.com/gogo/protobuf/proto"
	"google.golang.org/protobuf/proto"
)

// Marshal preserves the serialization helper provided by the previous gogo
// generated message.
func (x *CommonResp) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}

// Unmarshal preserves the deserialization helper provided by the previous
// gogo generated message.
func (x *CommonResp) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, x)
}

// Size preserves the size helper provided by the previous gogo generated
// message.
func (x *CommonResp) Size() int {
	return proto.Size(x)
}

// MarshalTo preserves the previous generated helper.
func (x *CommonResp) MarshalTo(buffer []byte) (int, error) {
	data, err := x.Marshal()
	if err != nil {
		return 0, err
	}
	if len(buffer) < len(data) {
		return 0, io.ErrShortBuffer
	}
	return copy(buffer, data), nil
}

// MarshalToSizedBuffer preserves the previous generated helper's behavior of
// writing the message at the end of the supplied buffer.
func (x *CommonResp) MarshalToSizedBuffer(buffer []byte) (int, error) {
	data, err := x.Marshal()
	if err != nil {
		return 0, err
	}
	if len(buffer) < len(data) {
		return 0, io.ErrShortBuffer
	}
	copy(buffer[len(buffer)-len(data):], data)
	return len(data), nil
}

// XXX_Unmarshal retains compatibility with code generated by older gogo
// protobuf versions.
func (x *CommonResp) XXX_Unmarshal(data []byte) error {
	return x.Unmarshal(data)
}

// XXX_Marshal retains compatibility with code generated by older gogo
// protobuf versions.
func (x *CommonResp) XXX_Marshal(buffer []byte, deterministic bool) ([]byte, error) {
	data, err := (proto.MarshalOptions{Deterministic: deterministic}).Marshal(x)
	if err != nil {
		return nil, err
	}
	if cap(buffer) < len(data) {
		return data, nil
	}
	buffer = buffer[:len(data)]
	copy(buffer, data)
	return buffer, nil
}

// XXX_Merge retains compatibility with code generated by older gogo protobuf
// versions.
func (x *CommonResp) XXX_Merge(source gogoproto.Message) {
	if source, ok := source.(*CommonResp); ok {
		proto.Merge(x, source)
	}
}

// XXX_Size retains compatibility with code generated by older gogo protobuf
// versions.
func (x *CommonResp) XXX_Size() int {
	return x.Size()
}

// XXX_DiscardUnknown retains compatibility with code generated by older gogo
// protobuf versions.
func (x *CommonResp) XXX_DiscardUnknown() {
	if x != nil {
		x.ProtoReflect().SetUnknown(nil)
	}
}
